version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django-dev-network

  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - .:/code
    networks:
      - django-dev-network


volumes:
  postgres_data:

networks:
  django-dev-network: